app.factory("yFac", function(){
  var o={};
  o.covers=[{artist:'sugarhill',
                  name:"rapper's delight",   
                  pic:'./images/covers/sugarhill.jpg',
                  link:'https://www.youtube.com/watch?v=rKTUAESacQM',
                  starttime: 9,
                  endtime: 11,
                 },
                 {artist:'DEF JEF',
                  name:"Here We Go Again",   
                  pic:'./images/covers/def_jef_here_we_go_again.jpg',
                  link:'https://www.youtube.com/watch?v=c1XXi93F0lg',
                  starttime: 19,
                  endtime: 20,
                 },
                 {artist:'Black Eyed Peas',
                  name:"Bridging the Gap",   
                  pic:'./images/covers/Black_Eyed_Peas_-_Bridging_the_Gap.jpg',
                  link:'https://en.wikipedia.org/wiki/Bridging_the_Gap_(Black_Eyed_Peas_album)',
                  starttime: 21,
                  endtime: 26,
                 },
                 {artist:'Audio Two',
                  name:"What More Can I Say?",   
                  pic:'./images/covers/AudioTwo.jpg',
                  link:'https://www.youtube.com/watch?v=I3_4Y7BlF9I',
                  starttime: 32,
                  endtime: 34,
                 },
                 {artist:'nwa',
                  name:"Greatest Hits",   
                  pic:'./images/covers/nwa.jpg',
                  link:'https://www.youtube.com/watch?v=n3Jwxs9b_gE&list=PLB91F90C64D681FE8',
                  starttime: 35,
                  endtime: 36,
                 },
                 {artist:'Black Sheep',
                  name:"A Wolf in Sheep's Clothing",   
                  pic:'./images/covers/BlackSheep.jpg',
                  link:'https://www.youtube.com/watch?v=tuCQiQ0A8Bw',
                  starttime: 37,
                  endtime: 48,
                 },
                 {artist:'MCCOY TYNER',
                  name:"ELVIN SIR JONES",   
                  pic:'./images/covers/MCCOY_TYNER_ELVIN_SIR_JONES.jpg',
                  link:'https://www.youtube.com/watch?v=jGpaBE7Vku0',
                  starttime: 39,
                  endtime: 48,
                 },
                 {artist:'Queen Latifah',
                  name:"All Hail the Queen",   
                  pic:'./images/covers/queen.jpg',
                  link:'https://www.youtube.com/watch?v=fU-5dNqNvD0',
                  starttime: 57,
                  endtime: 58,
                 },
                 {artist:'Run–D.M.C.',
                  name:"Tougher Than Leather",   
                  pic:'./images/covers/tougher.jpg',
                  link:'https://www.youtube.com/watch?v=PFvYm-i3vls',
                  starttime: 59,
                  endtime: 61,
                 },
                 {artist:'Ice-T',
                  name:"Power",   
                  pic:'./images/covers/power.jpg',
                  link:'https://www.youtube.com/watch?v=7K03hFhiW9E',
                  starttime: 62,
                  endtime: 64,
                 },
                 {artist:'digable planets',
                  name:"Reachin' (A New Refutation of Time and Space)",   
                  pic:'./images/covers/reachin.jpg',
                  link:'https://www.youtube.com/watch?v=Q3698kK8wGc',
                  starttime: 66,
                  endtime: 75,
                 },
                 {artist:'Art Blakey & The Jazz Messengers',
                  name:"Reflections In Blue",   
                  pic:'./images/covers/Reflections.jpg',
                  link:'https://www.youtube.com/watch?v=9NIXnkHu7UY',
                  starttime: 67,
                  endtime: 73,
                 },
                 {artist:'Digable Planets',
                  name:"Rebirth Of Slick (Cool Like Dat)",   
                  pic:'./images/covers/rebirth.jpg',
                  link:'https://www.youtube.com/watch?v=cM4kqL13jGM',
                  starttime: 67,
                  endtime: 73,
                 },
                 {artist:'Digable Planets',
                  name:"Beyond The Spectrum: The Creamy Spy Chronicles",   
                  pic:'./images/covers/beyond.jpg',
                  link:'http://www.discogs.com/Digable-Planets-Beyond-The-Spectrum-The-Creamy-Spy-Chronicles/master/19978',
                  starttime: 76,
                  endtime: 82,
                 },
                 {artist:'De La Soul',
                  name:"3 Feet High And Rising",   
                  pic:'./images/covers/3 Feet High And Rising.jpg',
                  link:'https://youtu.be/z1CaN4thI5w',
                  starttime: 85,
                  endtime: 101,
                 },
                 {artist:'De La Soul',
                  name:"De La Soul Is Dead",   
                  pic:'./images/covers/De La Soul Is Dead.jpg',
                  link:'https://youtu.be/SSOxle8AsHU',
                  starttime: 88,
                  endtime: 100,
                 },
                 {artist:'Doug E. Fresh & the Get Fresh Crew',
                  name:"The World's Greatest Entertainer",   
                  pic:'./images/covers/doug.jpg',
                  link:'https://www.youtube.com/watch?v=gLDyw8hYvpI',
                  starttime: 100,
                  endtime: 103,
                 },
                 {artist:'X-Clan',
                  name:"The One / Blackwards Row",   
                  pic:'./images/covers/xclan.jpg',
                  link:'http://www.discogs.com/X-Clan-The-One-Blackwards-Row/release/1481755',
                  starttime: 103,
                  endtime: 105,
                 },
                ]; 
    
    return o;

});